# Generated by Django 2.2.11 on 2020-03-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='poly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data1', models.FloatField()),
                ('data2', models.FloatField()),
                ('year', models.IntegerField()),
                ('prefecture', models.CharField(max_length=20)),
                ('pop', models.IntegerField()),
            ],
        ),
    ]
