# Generated by Django 2.2.11 on 2020-03-07 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotlyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='poly',
            new_name='Plotly',
        ),
    ]
