# Generated by Django 2.2.11 on 2020-03-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotlyapp', '0002_auto_20200308_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotly',
            name='area',
            field=models.CharField(max_length=20, null=True, verbose_name='area'),
        ),
        migrations.AlterField(
            model_name='plotly',
            name='data1',
            field=models.FloatField(verbose_name='data1'),
        ),
        migrations.AlterField(
            model_name='plotly',
            name='data2',
            field=models.FloatField(verbose_name='data2'),
        ),
        migrations.AlterField(
            model_name='plotly',
            name='pop',
            field=models.IntegerField(verbose_name='pop'),
        ),
        migrations.AlterField(
            model_name='plotly',
            name='prefecture',
            field=models.CharField(max_length=20, verbose_name='prefecture'),
        ),
        migrations.AlterField(
            model_name='plotly',
            name='year',
            field=models.IntegerField(verbose_name='year'),
        ),
    ]
